### ISSUE TITLE
Service offline?

### ISSUE THREAD

**Issue by Relequestual** [emanuelef/gh-repo-stats-server#9]
Hello!

It looks like the URL/IP you call when fetching the data returns 404s.
Maybe it changed IP or something?

Thanks for building and making it open source all the same =]

**Comment by Relequestual** [comment]
OK, well looks like it's working again. Maybe I just got unlucky. Solar flares.

**Comment by emanuelef** [comment]
Hi @Relequestual , just seen that now.
This tool has some limitations and I also need to improve the error reporting.
Happy to know if you have any comments/suggestion or a new feature.
